### PR TITLE
Fix compatability with BepInEx BE

### PR DESCRIPTION
**Pull request by timedroid**
Tested (partially) working with BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.663+5796f53 and the latest version of the game (1.9.0.0)

Have not tested focus patch or Hori Taiko Dru

### CODE REVIEW

**Comment by Fluto** [comment]
I wasn't expecting a pull request! I was going to look into it towards the end of the year 😅

Good work so far, saves me some time :p. Let me know when you reckon it's good enough for a review. 

Sorry you have to dig through the codebase. Patching il2cpp isn't my strongsuit, it's full of hacks and compromises.

**Comment by timedroid** [comment]
The converter and custom songs seem to be working now. I saw a couple conversion failures and at least one chart that had off notes; but I'm assuming that's not changed (I hadn't tried it previously and don't have older copies of the game).

**Comment by bendevnull** [comment]
If I can get a built version, I can test the Hori Drum compat

**Comment by bendevnull** [comment]
I'd also like to note it would be both the Switch and PS4 Hori cons

**Comment by cjrobe** [comment]
I assume this discussion is related to why BepInEx says "0 plugins to load"? I followed the guide and placed "com.fluto.takotako" in the plugins folder but nothing happens. Thanks for your guys work on this.

```
[Message: Preloader] BepInEx 6.0.0-be.664 - Taiko no Tatsujin
[Message: Preloader] Built from commit 0b23557c1355913983f3540797fa22c43a02247d
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.38f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

**Comment by alexankitty** [comment]
I built it myself and tried the switch hori drum and worked just fine.
Attached is the built binary I used from the pr branch.
[com.fluto.takotako.zip](https://github.com/Fluto/TakoTako/files/10354291/com.fluto.takotako.zip)

**Comment by Fluto** [comment]
This looks great, simply updating BepInEx to the latest version, sorry for the delay!

**Pull request merged**
